version: '3.8'

services:

  sendgrid:
    image: ghashange/sendgrid-mock:1.9.0
    restart: unless-stopped

    environment:
      - API_KEY=${SENDGRID_API_KEY}
      - CERT_DOMAINNAMES="localhost"

    ports:
      - 3000:3000
