name: Formatter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev

  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup the environment
        uses: ./.github/actions/build_app

      - name: Check the format
        run: poetry run python -m black --check async_sendgrid
