name: Integration Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - dev

  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      sendgrid:
        image: ghashange/sendgrid-mock:1.9.0
        env:
          API_KEY: SG.test123
        ports:
          - 3000:3000

    strategy:
      matrix:
        python-version: ["3.10.13", "3.11.5", "3.12.0", "3.13.2"]

    env:
      POETRY_NO_INTERACTION: 1
      PIP_DEFAULT_TIMEOUT: 100

    steps:
      - name: Setup the environment
        uses: ./.github/actions/build_app
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: poetry run python -m pytest -k integration --cov=async-sendgrid tests
