name: Integration Tests

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10.13', '3.11.5', '3.12.0']

    env:
      POETRY_NO_INTERACTION: 1
      PIP_DEFAULT_TIMEOUT: 100  

    steps:

      - name: Setup the environment
        uses: EM51641/async-sendgrid/.github/actions/build_app@main
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: poetry run python -m pytest --cov=async-sendgrid tests