name: Linting

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - dev

  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup the environment
        uses: EM51641/async-sendgrid/.github/actions/build_app@main

      - name: Check the linting
        run: poetry run python -m flake8 async_sendgrid
