name: Linting

on:
  pull_request:
    types: [opened, synchronize]

  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup the environment
        uses: ./.github/actions/build_app

      - name: Check the linting
        run: poetry run python -m flake8 async_sendgrid
