# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release and Upload Python Package on PyPI

on:
  push:
    branches:
      - main

jobs:
  unit:
    name: Call unit tests
    uses: ./.github/workflows/unit.yaml

  typing:
    name: Call mypy
    uses: ./.github/workflows/typing.yaml

  linting:
    name: Call flake8
    uses: ./.github/workflows/linting.yaml

  formatter:
    name: Call black
    uses: ./.github/workflows/formatter.yaml

  integration:
    name: Call integration tests
    uses: ./.github/workflows/integration.yaml

  release:
    runs-on: ubuntu-latest
    name: Release version
    needs: [unit, typing, linting, formatter, integration]

    permissions:
      contents: write

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Production Build"
          files: |
            LICENSE.txt
            *.jar

  deploy:
    needs: [release]
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Setup the environment
        uses: ./.github/actions/build_app

      - name: Install Dependencies
        run: poetry install --no-root

      - name: Build package
        run: poetry build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
