name: Typing

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize]
    branches:
      - dev
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup the environment
        uses: ./.github/actions/build_app

      - name: Check the typing
        run: poetry run python -m mypy async_sendgrid
