name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev

  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      POETRY_NO_INTERACTION: 1
      PIP_DEFAULT_TIMEOUT: 100

    steps:
      - name: Setup the environment
        uses: ./.github/actions/build_app

      - name: Run tests
        run: poetry run python -m pytest -k unit --cov=async_sendgrid tests

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
