name: Unit Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      POETRY_NO_INTERACTION: 1
      PIP_DEFAULT_TIMEOUT: 100  

    steps:
      - name: Setup the environment
        uses: EM51641/async-sendgrid/.github/actions/build_app@main

      - name: Run tests
        run: poetry run python -m pytest --cov=async_sendgrid tests

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
